# login theme properties: login/theme.properties

parent=keycloak
name=Login
import=common/keycloak
styles=css/login.css

favIcon=${url.resourcesPath}/img/favicon.ico
favicon=${url.resourcesPath}/img/favicon.ico
favicons=${url.resourcesPath}/img/favicon.ico
